name: build-and-deploy

on:
  push:
    branches: [main]
    paths:
      - "glyph_codex.xlsx"
      - "src/**"
      - "package.json"
      - "vite.config.*"
      - ".github/workflows/build.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Set up Node
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 3. Convert Excel → JSON
      - name: Convert Excel to JSON
        run: |
          python -m pip install pandas openpyxl --quiet
          python - <<'PY'
          import pandas as pd, pathlib, json
          keep = ["Name", "Level", "New Text", "Higher Tiers"]  # exact headers!
          df = pd.read_excel("glyph_codex.xlsx", engine="openpyxl")[keep]
          pathlib.Path("public").mkdir(exist_ok=True)
          df.to_json("public/glyphs.json", orient="records", indent=2, force_ascii=False)
          print("Wrote public/glyphs.json")
          PY

      # 4. Install deps & build Vite
      - run: npm ci
      - run: npm run build      # outputs to dist/

      # 5. Upload artifact for Pages
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
